export default {
  root: {
    width: '50%',
    marginTop: 50,
    marginBottom: 20,
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  description: {
    color: '#545252',
  },
  label: {
    marginBottom: 10,
  },
  inlinebox: {
    display: 'inline-block',
    width: '40%',
    height: '100px',
    margin: '1em',
  },
  valueTextSpace: {
    marginTop: '20px',
  },
  valueText: {
    background: '#c1c1c1',
    margin: 'auto',
    width: '400px',
    padding: '10px',
    marginTop: '20px',
    marginRight: '10px',
  },
  code: {
    margin: '10px 0',
    textAlign: 'left',
  },
  info: {
    fontStyle: 'italic',
    color: '#3131d4',
    fontSize: 15,
    margin: '5px 0',
  },
  sliderWrapper: {
    width: '75%',
  },
  slider: {
    height: 40,
  },
  trackStyle: {
    position: 'relative',
    textAlign: 'left',
    border: 'none',
    backgroundColor: '#f0f0f0',
  },
  highlightedTrackStyle: {
    height: 5,
    border: 'none',
    background: '#3e99fd',
    // border: '3px solid #3e99fd',
    //backgroundColor: 'grey',
    // top: 14,
  },
  handleStyle: {
    // height: 30,
    // width: 30,
    // border: '5px solid #e9dfdf',
    // backgroundColor: '#2771e2',

    position: 'absolute',
    zIndex: 2,
    width: 15,
    height: 15,
    cursor: 'default',
    touchAction: 'none',
    border: '3px #fff solid',
    background: '#3e99fd',
    borderRadius: '100%',
    outline: 'none',
    boxShadow: '1px 1px 5px rgba(0, 0, 0, 0.3)',
  },
  hoveredHandleStyle: {
    position: 'absolute',
    zIndex: 2,
    width: 15,
    height: 15,
    cursor: 'default',
    touchAction: 'none',
    border: '3px #3e99fd solid',
    background: '#fff !important',
    borderRadius: '100%',
    outline: 'none',
    boxShadow: '1px 1px 5px rgba(0, 0, 0, 0.3)',
  },
  activeHandleStyle: {
    position: 'absolute',
    zIndex: 2,
    width: 15,
    height: 15,
    cursor: 'default',
    touchAction: 'none',
    border: '3px #3e99fd solid',
    background: '#fff !important',
    borderRadius: '100%',
    outline: 'none',
    boxShadow: '1px 1px 5px rgba(0, 0, 0, 0.3)',
  },
  focusedHandleStyle: {
    position: 'absolute',
    zIndex: 2,
    width: 15,
    height: 15,
    cursor: 'default',
    touchAction: 'none',
    border: '3px #fff solid',
    background: '#3e99fd',
    borderRadius: '100%',
    outline: 'none',
    boxShadow: '1px 1px 5px rgba(0, 0, 0, 0.3)',
  },
};
